import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-fleet-fuel-excise-tax-refund",
  "engine": "recovery",
  "title": "Fleet Fuel Excise Tax Refund",
  "shortTitle": "Fleet Fuel Excise Tax Refund",
  "tagline": "Quantify, recover, and prevent financial leakage through fleet fuel excise tax refund",
  "industry": "Fleet Tax Recovery",
  "uiPort": 4625,
  "apiPort": 5625,
  "accent": "#be123c",
  "currency": "USD",
  "primaryOutcome": "Fleet Fuel Excise Tax Refund converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect entities, jurisdictions, vehicles, equipment, fuel-card transactions, bulk receipts, assignments, telematics, engine hours, tax-paid gallons, eligible uses, filings, and refunds in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "receivedRefund",
    "expectedKey": "eligibleRefund",
    "actualLabel": "Received Tax Refund",
    "expectedLabel": "Calculated Eligible Refund",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Fleet Fuel Excise Tax Refund evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("entity-jurisdiction-registry","FFE01","Entity jurisdiction registry","Execute entity jurisdiction registry using entities, jurisdictions, vehicles, equipment, fuel-card transactions, bulk receipts, assignments, telematics, engine hours, tax-paid gallons, eligible uses, filings, and refunds.","Produce a governed entity jurisdiction registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fleet / Tax Jurisdiction","text","Fleet / Tax Jurisdiction · Standard Case"],["caseReference","Entity jurisdiction registry Reference","text","FFE01-2026-001"],["receivedRefund","Received Tax Refund","currency",1049000],["eligibleRefund","Calculated Eligible Refund","currency",1237820],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity jurisdiction registry case","Vehicle equipment master case","Fuel-card ingestion case","Bulk fuel receipt ingestion case","Asset assignment case"]}),
feature("vehicle-equipment-master","FFE02","Vehicle equipment master","Execute vehicle equipment master using entities, jurisdictions, vehicles, equipment, fuel-card transactions, bulk receipts, assignments, telematics, engine hours, tax-paid gallons, eligible uses, filings, and refunds.","Produce a governed vehicle equipment master decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fleet / Tax Jurisdiction","text","Fleet / Tax Jurisdiction · Standard Case"],["caseReference","Vehicle equipment master Reference","text","FFE02-2026-001"],["receivedRefund","Received Tax Refund","currency",1049000],["eligibleRefund","Calculated Eligible Refund","currency",1237820],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity jurisdiction registry case","Vehicle equipment master case","Fuel-card ingestion case","Bulk fuel receipt ingestion case","Asset assignment case"]}),
feature("fuel-card-ingestion","FFE03","Fuel-card ingestion","Execute fuel-card ingestion using entities, jurisdictions, vehicles, equipment, fuel-card transactions, bulk receipts, assignments, telematics, engine hours, tax-paid gallons, eligible uses, filings, and refunds.","Produce a governed fuel-card ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fleet / Tax Jurisdiction","text","Fleet / Tax Jurisdiction · Standard Case"],["caseReference","Fuel-card ingestion Reference","text","FFE03-2026-001"],["receivedRefund","Received Tax Refund","currency",1049000],["eligibleRefund","Calculated Eligible Refund","currency",1237820],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity jurisdiction registry case","Vehicle equipment master case","Fuel-card ingestion case","Bulk fuel receipt ingestion case","Asset assignment case"]}),
feature("bulk-fuel-receipt-ingestion","FFE04","Bulk fuel receipt ingestion","Execute bulk fuel receipt ingestion using entities, jurisdictions, vehicles, equipment, fuel-card transactions, bulk receipts, assignments, telematics, engine hours, tax-paid gallons, eligible uses, filings, and refunds.","Produce a governed bulk fuel receipt ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fleet / Tax Jurisdiction","text","Fleet / Tax Jurisdiction · Standard Case"],["caseReference","Bulk fuel receipt ingestion Reference","text","FFE04-2026-001"],["receivedRefund","Received Tax Refund","currency",1049000],["eligibleRefund","Calculated Eligible Refund","currency",1237820],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity jurisdiction registry case","Vehicle equipment master case","Fuel-card ingestion case","Bulk fuel receipt ingestion case","Asset assignment case"]}),
feature("asset-assignment","FFE05","Asset assignment","Execute asset assignment using entities, jurisdictions, vehicles, equipment, fuel-card transactions, bulk receipts, assignments, telematics, engine hours, tax-paid gallons, eligible uses, filings, and refunds.","Produce a governed asset assignment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fleet / Tax Jurisdiction","text","Fleet / Tax Jurisdiction · Standard Case"],["caseReference","Asset assignment Reference","text","FFE05-2026-001"],["receivedRefund","Received Tax Refund","currency",1049000],["eligibleRefund","Calculated Eligible Refund","currency",1237820],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity jurisdiction registry case","Vehicle equipment master case","Fuel-card ingestion case","Bulk fuel receipt ingestion case","Asset assignment case"]}),
feature("telematics-matching","FFE06","Telematics matching","Execute telematics matching using entities, jurisdictions, vehicles, equipment, fuel-card transactions, bulk receipts, assignments, telematics, engine hours, tax-paid gallons, eligible uses, filings, and refunds.","Produce a governed telematics matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fleet / Tax Jurisdiction","text","Fleet / Tax Jurisdiction · Standard Case"],["caseReference","Telematics matching Reference","text","FFE06-2026-001"],["receivedRefund","Received Tax Refund","currency",1049000],["eligibleRefund","Calculated Eligible Refund","currency",1237820],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity jurisdiction registry case","Vehicle equipment master case","Fuel-card ingestion case","Bulk fuel receipt ingestion case","Asset assignment case"]}),
feature("engine-hour-matching","FFE07","Engine-hour matching","Execute engine-hour matching using entities, jurisdictions, vehicles, equipment, fuel-card transactions, bulk receipts, assignments, telematics, engine hours, tax-paid gallons, eligible uses, filings, and refunds.","Produce a governed engine-hour matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fleet / Tax Jurisdiction","text","Fleet / Tax Jurisdiction · Standard Case"],["caseReference","Engine-hour matching Reference","text","FFE07-2026-001"],["receivedRefund","Received Tax Refund","currency",1049000],["eligibleRefund","Calculated Eligible Refund","currency",1237820],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity jurisdiction registry case","Vehicle equipment master case","Fuel-card ingestion case","Bulk fuel receipt ingestion case","Asset assignment case"]}),
feature("tax-paid-gallon-calculation","FFE08","Tax-paid gallon calculation","Execute tax-paid gallon calculation using entities, jurisdictions, vehicles, equipment, fuel-card transactions, bulk receipts, assignments, telematics, engine hours, tax-paid gallons, eligible uses, filings, and refunds.","Produce a governed tax-paid gallon calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fleet / Tax Jurisdiction","text","Fleet / Tax Jurisdiction · Standard Case"],["caseReference","Tax-paid gallon calculation Reference","text","FFE08-2026-001"],["receivedRefund","Received Tax Refund","currency",1049000],["eligibleRefund","Calculated Eligible Refund","currency",1237820],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity jurisdiction registry case","Vehicle equipment master case","Fuel-card ingestion case","Bulk fuel receipt ingestion case","Asset assignment case"]}),
feature("eligible-use-classification","FFE09","Eligible use classification","Execute eligible use classification using entities, jurisdictions, vehicles, equipment, fuel-card transactions, bulk receipts, assignments, telematics, engine hours, tax-paid gallons, eligible uses, filings, and refunds.","Produce a governed eligible use classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fleet / Tax Jurisdiction","text","Fleet / Tax Jurisdiction · Standard Case"],["caseReference","Eligible use classification Reference","text","FFE09-2026-001"],["receivedRefund","Received Tax Refund","currency",1049000],["eligibleRefund","Calculated Eligible Refund","currency",1237820],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity jurisdiction registry case","Vehicle equipment master case","Fuel-card ingestion case","Bulk fuel receipt ingestion case","Asset assignment case"]}),
feature("federal-refund-calculation","FFE10","Federal refund calculation","Execute federal refund calculation using entities, jurisdictions, vehicles, equipment, fuel-card transactions, bulk receipts, assignments, telematics, engine hours, tax-paid gallons, eligible uses, filings, and refunds.","Produce a governed federal refund calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fleet / Tax Jurisdiction","text","Fleet / Tax Jurisdiction · Standard Case"],["caseReference","Federal refund calculation Reference","text","FFE10-2026-001"],["receivedRefund","Received Tax Refund","currency",1049000],["eligibleRefund","Calculated Eligible Refund","currency",1237820],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity jurisdiction registry case","Vehicle equipment master case","Fuel-card ingestion case","Bulk fuel receipt ingestion case","Asset assignment case"]}),
feature("state-refund-calculation","FFE11","State refund calculation","Execute state refund calculation using entities, jurisdictions, vehicles, equipment, fuel-card transactions, bulk receipts, assignments, telematics, engine hours, tax-paid gallons, eligible uses, filings, and refunds.","Produce a governed state refund calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fleet / Tax Jurisdiction","text","Fleet / Tax Jurisdiction · Standard Case"],["caseReference","State refund calculation Reference","text","FFE11-2026-001"],["receivedRefund","Received Tax Refund","currency",1049000],["eligibleRefund","Calculated Eligible Refund","currency",1237820],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity jurisdiction registry case","Vehicle equipment master case","Fuel-card ingestion case","Bulk fuel receipt ingestion case","Asset assignment case"]}),
feature("evidence-package","FFE12","Evidence package","Execute evidence package using entities, jurisdictions, vehicles, equipment, fuel-card transactions, bulk receipts, assignments, telematics, engine hours, tax-paid gallons, eligible uses, filings, and refunds.","Produce a governed evidence package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fleet / Tax Jurisdiction","text","Fleet / Tax Jurisdiction · Standard Case"],["caseReference","Evidence package Reference","text","FFE12-2026-001"],["receivedRefund","Received Tax Refund","currency",1049000],["eligibleRefund","Calculated Eligible Refund","currency",1237820],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity jurisdiction registry case","Vehicle equipment master case","Fuel-card ingestion case","Bulk fuel receipt ingestion case","Asset assignment case"]}),
feature("form-preparation","FFE13","Form preparation","Execute form preparation using entities, jurisdictions, vehicles, equipment, fuel-card transactions, bulk receipts, assignments, telematics, engine hours, tax-paid gallons, eligible uses, filings, and refunds.","Produce a governed form preparation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fleet / Tax Jurisdiction","text","Fleet / Tax Jurisdiction · Standard Case"],["caseReference","Form preparation Reference","text","FFE13-2026-001"],["receivedRefund","Received Tax Refund","currency",1049000],["eligibleRefund","Calculated Eligible Refund","currency",1237820],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity jurisdiction registry case","Vehicle equipment master case","Fuel-card ingestion case","Bulk fuel receipt ingestion case","Asset assignment case"]}),
feature("refund-tracking","FFE14","Refund tracking","Execute refund tracking using entities, jurisdictions, vehicles, equipment, fuel-card transactions, bulk receipts, assignments, telematics, engine hours, tax-paid gallons, eligible uses, filings, and refunds.","Produce a governed refund tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fleet / Tax Jurisdiction","text","Fleet / Tax Jurisdiction · Standard Case"],["caseReference","Refund tracking Reference","text","FFE14-2026-001"],["receivedRefund","Received Tax Refund","currency",1049000],["eligibleRefund","Calculated Eligible Refund","currency",1237820],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity jurisdiction registry case","Vehicle equipment master case","Fuel-card ingestion case","Bulk fuel receipt ingestion case","Asset assignment case"]}),
feature("fleet-jurisdiction-analytics","FFE15","Fleet jurisdiction analytics","Execute fleet jurisdiction analytics using entities, jurisdictions, vehicles, equipment, fuel-card transactions, bulk receipts, assignments, telematics, engine hours, tax-paid gallons, eligible uses, filings, and refunds.","Produce a governed fleet jurisdiction analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fleet / Tax Jurisdiction","text","Fleet / Tax Jurisdiction · Standard Case"],["caseReference","Fleet jurisdiction analytics Reference","text","FFE15-2026-001"],["receivedRefund","Received Tax Refund","currency",1049000],["eligibleRefund","Calculated Eligible Refund","currency",1237820],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedRefund",subjects:["Entity jurisdiction registry case","Vehicle equipment master case","Fuel-card ingestion case","Bulk fuel receipt ingestion case","Asset assignment case"]})
]);
